apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
        - name: website
          image: wujiayi1986/ecom-web:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: app-cm