---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-statefulset
  labels: &labels
    app: mysql
    component: statefulset
spec:
  serviceName: mysql-statefulset
  replicas: 1
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      containers:
      - name: mysql
        image: mariadb:latest
        ports:
          - containerPort: 3306
        volumeMounts:
          - name: script-volume
            mountPath: /docker-entrypoint-initdb.d
        envFrom:
          - configMapRef:
              name: db-cm
      volumes:
        - name: script-volume
          configMap:
            name: db-cm