---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels: &labels
    app: mysql
    component: service
spec:
  clusterIP: None
  selector:
    app: mysql
    component: statefulset
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306